### ISSUE TITLE
agronomicCropFamily or agronomicCropCategory?

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0265#16]
In botanicalPlantType we have an element named agronomicCropFamily of type agronomicCropCategoryType.

Either:
name the element botanicalPlant:gronomicCropFamily agronomicCropCategory

Or:
name the element agronomicCropCategory agronomicCropFamily

**Comment by anjaaeschlimann** [comment]
i'd go for
Element: agronomicCropCategroy
Datentyp: agronomicCropCategoryType
